# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-25 00:41
from __future__ import unicode_literals

from django.db import migrations
import stdimage.models
import stdimage.utils


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='album',
            options={'verbose_name': 'Album', 'verbose_name_plural': 'Albums'},
        ),
        migrations.AlterModelOptions(
            name='photo',
            options={'verbose_name': 'Photo', 'verbose_name_plural': 'Photos'},
        ),
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=stdimage.models.StdImageField(upload_to=stdimage.utils.UploadToClassNameDir(), verbose_name='Image'),
        ),
    ]
