# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-25 10:24
from __future__ import unicode_literals

from django.db import migrations
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_auto_20171025_0041'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='cropping',
            field=image_cropping.fields.ImageRatioField('image', '100x100', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=True, verbose_name='Cropping of Photo'),
        ),
    ]
